Session start issue
mParticle/mparticle-roku-sdk pull request #12
Opened 2020-10-12 21:17 UTC by BrandonStalnaker

# Summary

In our Livestream, the regular events event have the same session_id and session_uuid but Session Start has a different one which is incorrect.

2020-10-12 22:42 UTC, alexs-mparticle approved these changes

2020-10-12 22:43 UTC, alexs-mparticle commented
LGTM, just update the Summary to explain the history and difference between `sid` and `id` for posterity.

2020-10-13 12:58 UTC, samdozor requested changes
- I'd like to make sure that the formatting change ends up in the history as a separate commit, so that in the future on a `git blame`, these lines are shown as changing for the right reasons. Can you separate the style change into a separate PR?

- Please also re-write your commit messages to be more consistent with the commits of the roku repo:

<img width="515" alt="Screen Shot 2020-10-13 at 8 48 54 AM" src="https://user-images.githubusercontent.com/1761038/95862589-20378480-0d31-11eb-8089-eda90f3c6947.png">

"Formatting for change to using VSCode" <-- commits should not refer to themselves in the 3rd person, and the "to using" is awkward grammar. And who is using vscode? I took a look at the vscode plugin, and actually it's [using this project under the hood](https://github.com/RokuCommunity/brighterscript-formatter). So it's more accurate to describe this as something like "Reformat code with brighterscript-formatter"

"The id of the session start event is the sid" <-- commit shouldn't state fact like this. This would be as if we had other commits such as "The SDK version is 1.2". How about "Use the session ID as the session start message ID" - and then you can include a longer description on the 3rd line of the commit message describing why this change was needed.

2020-10-13 12:58 UTC, samdozor commented on mParticleCore.brs
> +' Copyright 2019 mParticle, Inc. test
oops ^^

2020-10-13 14:52 UTC, BrandonStalnaker commented
@samdozor Yeah I was writing those more explain to each other and was planning to write a better commit message with the merge commit. You're right though. The commits should be kept separate. Here's the formatting commit. https://github.com/mParticle/mparticle-roku-sdk/pull/13

2020-10-13 17:45 UTC, BrandonStalnaker commented
Made a new PR https://github.com/mParticle/mparticle-roku-sdk/pull/14

2020-10-13 17:45 UTC, closed without merging