Feature:expose session info as scenegraph node
mParticle/mparticle-roku-sdk pull request #38
Opened 2023-11-15 23:52 UTC by mmustafa-tse

## Instructions
 1. PR target branch should be against `development`
 2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
 3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

 ## Summary
 - We have a GAP request by multiple clients to expose the session info including the sessionId to match the other SDKs

 ## Testing Plan
 - [Y] Was this tested locally? If not, explain why.
 - added the coded locally to my Roku project and was able to view the session information as a scenegraph node.

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/REPLACEME

2023-11-22 12:48 UTC, BrandonStalnaker approved these changes
LGTM

2023-11-22 12:50 UTC, BrandonStalnaker requested changes, later dismissed
Just needs testing

2023-11-27 13:48 UTC, BrandonStalnaker approved these changes
LGTM

2023-11-29 15:46 UTC, samdozor approved these changes

2023-11-29 15:47 UTC, merged