Collect GDPR and CCPA Consent State
mParticle/mparticle-roku-sdk pull request #5
Opened 2020-03-03 21:20 UTC by alexs-mparticle

2020-03-03 23:09 UTC, rmi22186 reviewed
looks good. small nits. but i'd like to grab some time to review a couple small lines in person which i noted, and also once consent is granted to the specific workspace, would be great to see it flowing end to end.

2020-03-03 23:09 UTC, rmi22186 commented on mParticleCore.brs
> +        getGDPRConsentState : function (consentState as object, purpose as string)
`getGDPRConsentState` shouldn't take any arguments. it should just return the GDPRConsentState.  it's up to the developer if they want to then lookup a purpose on it

2020-03-03 23:09 UTC, rmi22186 commented on mParticleCore.brs
> +        sendUserAttributeChangeEvent: function(attributeKey as string, newUserAttributeValue as string, previousUserAttribute as string, isNewAttribute as boolean, deleted as boolean) as void
i think this is part of the leanplum bug, you can probably remove

2020-03-03 23:09 UTC, rmi22186 commented on mParticleCore.brs
> +        storage.setConsentState = function(mpid as string, consentState as object) as void
this block of code is a bit confusing to me. let's review in person

2020-03-05 15:33 UTC, samdozor requested changes

2020-03-05 15:33 UTC, samdozor commented on mParticleCore.brs
> +        build : function (document="" as string, consented=false as boolean, location="" as string, timestamp=0 as longInteger, hardwareId="" as string)
is there any reason to default these to empty string? better to upload them as null if not included. same comment above on line 177.

2020-03-05 15:33 UTC, samdozor commented on mParticleCore.brs
> +            attributeJson = m.get(m.mpkeys.CONSENT_STATE + mpid)
```suggestion
            consentJson = m.get(m.mpkeys.CONSENT_STATE + mpid)
```

2020-03-11 14:15 UTC, rmi22186 commented
@samdozor - any final feedback on this?

2020-03-11 14:18 UTC, samdozor approved these changes

2020-03-11 14:47 UTC, merged